#!/usr/bin/env ruby

require 'rubygems'
require 'commander/import'
require_relative 'pomegranate'

program :version, '0.0.1'
program :description, 'A tool for creating a json file to represent your tutorials'
 
command :init do |c|
  c.syntax = 'pomegranate-cli init, [options]'
  c.summary = ''
  c.description = ''
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |args, options|
    Pomegranate.new_file
  end
end

command :edit do |c|
  c.syntax = 'pomegranate-cli edit [options]'
  c.summary = ''
  c.description = ''
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |args, options|
    # Do something or c.when_called Pomegranate-cli::Commands::Edit
  end
end

